package com.example.savemoney.data.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey


// Defines the ProductEntity data class, which represents a single product in the grocery list.
// This entity will be used to create a table named "Grocery_table" in the Room database.
@Entity(tableName = "Grocery_table")
data class GroceryEntity(

    // Represents a unique identifier for each product.
    // This field is the primary key for the table and is autogenerated.
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    // Represents the name of the product.
    // This field is stored in the "Grocery_name" column of the table.
    @ColumnInfo(name = "Grocery_name")
    val name: String = "",
    var isCompleted: Boolean = false, // The variable responsible for the strikethrough state.

    // Represents the quantity of the product (e.g., in kilograms, bottles, or packs).
    // This field is stored in the "Grocery_Quantity" column of the table.
    @ColumnInfo(name = "Grocery_Quantity")
    val quantity: String = "",

    @ColumnInfo(name = "Order_of_elements")
    var order: Int,

    @ColumnInfo(name = "creationTimestamp")
    val creationTimestamp: Long

)